name: nfc
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.0
  path: ^1.8.4
  nfc_manager: ^4.0.0
  ndef_record: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  sqflite_common_ffi: ^2.2.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
